displayName=Wilderness Sentinel
author=DGMushy
support=https://github.com/danieljglover/WildernessSentinel/issues
description=Alerts you when another player is detected nearby in the Wilderness with configurable filters, combat level detection, and screen flash
tags=wilderness,alert,alarm,detector,pk,players,sentinel,pker,pvp,escape
plugins=com.WildernessSentinel.WildernessSentinelPlugin
